window.FIG2B = [
  {
    "nct": "NCT04493242",
    "title": "Extracellular Vesicle Infusion Treatment for COVID-19 Associated ARDS",
    "ev_source": "Bone Marrow Derived Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 1050000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 1050000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": "https://clinicaltrials.gov/study/NCT04493242"
  },
  {
    "nct": "NCT04313647",
    "title": "A Tolerance Clinical Study on Aerosol Inhalation of Mesenchymal Stem Cells Exosomes In Healthy Volunteers",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 3200000000.0,
    "dose_unit": "nanovesicles/3 mL",
    "dose_scaled": 3200000000.0,
    "axis": "particles",
    "route": "Inhalation",
    "url": "https://clinicaltrials.gov/study/NCT04313647"
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 30000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 30000000000.0,
    "axis": "particles",
    "route": "Intradermal / topical",
    "url": ""
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 350000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 350000000000.0,
    "axis": "particles",
    "route": "Other",
    "url": ""
  },
  {
    "nct": "NCT05116761",
    "title": "ExoFlo‚Ñ¢ Infusion for Post-Acute COVID-19 and Chronic Post-COVID-19 Syndrome",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 1050000000.0,
    "dose_unit": "EVs",
    "dose_scaled": 1050000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": "https://clinicaltrials.gov/study/NCT05116761"
  },
  {
    "nct": "NCT04602104",
    "title": "A Clinical Study of Mesenchymal Stem Cell Exosomes Nebulizer for the Treatment of ARDS",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 1600000000.0,
    "dose_unit": "particles",
    "dose_scaled": 1600000000.0,
    "axis": "particles",
    "route": "Inhalation",
    "url": "https://clinicaltrials.gov/study/NCT04602104"
  },
  {
    "nct": "NCT06482541",
    "title": "Efficacy and Safety Of AGE ZERO‚Ñ¢ EXOSOMES To Treat Men and Women With Androgenetic Alopecia",
    "ev_source": "Wharton Jelly Derived Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 50000000000.0,
    "dose_unit": "exosomes",
    "dose_scaled": 50000000000.0,
    "axis": "particles",
    "route": "Intradermal / topical",
    "url": "https://clinicaltrials.gov/study/NCT06482541"
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 20000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 20000000000.0,
    "axis": "particles",
    "route": "Other",
    "url": ""
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 2400000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 2400000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": ""
  },
  {
    "nct": "NCT04747574",
    "title": "Evaluation of the Safety of CD24-Exosomes in Patients With COVID-19 Infection",
    "ev_source": "T-REx™-293 cells engineered to express CD24",
    "dose_raw": 10000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 10000000000.0,
    "axis": "particles",
    "route": "Inhalation",
    "url": "https://clinicaltrials.gov/study/NCT04747574"
  },
  {
    "nct": "NCT06202547",
    "title": "Intra-ovarian Injection of MSC-EVs in Idiopathic Premature Ovarian Failure",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 30000000000.0,
    "dose_unit": "Cells",
    "dose_scaled": 30000000000.0,
    "axis": "particles",
    "route": "Other",
    "url": "https://clinicaltrials.gov/study/NCT06202547"
  },
  {
    "nct": "NCT05125562",
    "title": "Extracellular Vesicles Infusion Treatment for Mild-to-Moderate COVID-19",
    "ev_source": "Bone Marrow Derived Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 1200000000000.0,
    "dose_unit": "EVs",
    "dose_scaled": 1200000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": "https://clinicaltrials.gov/study/NCT05125562"
  },
  {
    "nct": "NCT04491240",
    "title": "Evaluation of Safety and Efficiency of Method of Exosome Inhalation in SARS-CoV-2 Associated Pneumonia.",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 5000000000.0,
    "dose_unit": "exosomes/3mL",
    "dose_scaled": 5000000000.0,
    "axis": "particles",
    "route": "Inhalation",
    "url": "https://clinicaltrials.gov/study/NCT04491240"
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 2400000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 2400000000000.0,
    "axis": "particles",
    "route": "Other",
    "url": ""
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 2400000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 2400000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": ""
  },
  {
    "nct": "NCT05787288",
    "title": "A Clinical Study on Safety and Effectiveness of Mesenchymal Stem Cell Exosomes for the Treatment of COVID-19.",
    "ev_source": "Umbilical Cord Derived Mesenchymal Stem Cells (UCMSC)",
    "dose_raw": 5000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 5000000000.0,
    "axis": "particles",
    "route": "Inhalation",
    "url": "https://clinicaltrials.gov/study/NCT05787288"
  },
  {
    "nct": "NCT04969172",
    "title": "A Phase II Randomized, Double-blind, Placebo-controlled Study to Evaluate the Safety and Efficacy of Exosomes Overexpressing CD24 to Prevent Clinical Deterioration in Patients With Moderate or Severe COVID-19 Infection",
    "ev_source": "Human Embryonic Kidney Cells",
    "dose_raw": 100000000000.0,
    "dose_unit": "Exosome Particles",
    "dose_scaled": 100000000000.0,
    "axis": "particles",
    "route": "Other",
    "url": "https://clinicaltrials.gov/study/NCT04969172"
  },
  {
    "nct": "NCT04389385",
    "title": "COVID-19 Specific T Cell Derived Exosomes (CSTC-Exo)",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 200000000.0,
    "dose_unit": "nanovesicles/3 mL",
    "dose_scaled": 200000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": "https://clinicaltrials.gov/study/NCT04389385"
  },
  {
    "nct": "NCT05940610",
    "title": "The Safety and Efficacy of MSC-EVs in Acute/Acute-on-Chronic Liver Failure",
    "ev_source": "Mesenchymal Stem Cell (MSC)",
    "dose_raw": 100000000000.0,
    "dose_unit": "particles/100 mL",
    "dose_scaled": 100000000000.0,
    "axis": "particles",
    "route": "Inhalation",
    "url": "https://clinicaltrials.gov/study/NCT05940610"
  },
  {
    "nct": "NCT05774509",
    "title": "Treatment of Non-ischemic Cardiomyopathies by Intravenous Extracellular Vesicles of Cardiovascular Progenitor Cells",
    "ev_source": "cardiovascular progenitor cells (differentiated from human induced pluripotent stem cells)",
    "dose_raw": 3000000000000.0,
    "dose_unit": "particles/kg",
    "dose_scaled": 3000000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": "https://clinicaltrials.gov/study/NCT05774509"
  },
  {
    "nct": "NCT04276987",
    "title": "A Pilot Clinical Study on Inhalation of Mesenchymal Stem Cells Exosomes Treating Severe Novel Coronavirus Pneumonia",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 200000000.0,
    "dose_unit": "exosomes/3mL",
    "dose_scaled": 200000000.0,
    "axis": "particles",
    "route": "Inhalation",
    "url": "https://clinicaltrials.gov/study/NCT04276987"
  },
  {
    "nct": "NCT06138210",
    "title": "The Effect of GD-iExo-003 in Acute Ischemic Stroke",
    "ev_source": "human induced pluripotent stem cell (GD-iExo-003)",
    "dose_raw": 600000000000.0,
    "dose_unit": "Particles/kg",
    "dose_scaled": 600000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": "https://clinicaltrials.gov/study/NCT06138210"
  },
  {
    "nct": "NCT04491240",
    "title": "Evaluation of Safety and Efficiency of Method of Exosome Inhalation in SARS-CoV-2 Associated Pneumonia.",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 20000000000.0,
    "dose_unit": "exosomes/3mL",
    "dose_scaled": 20000000000.0,
    "axis": "particles",
    "route": "Inhalation",
    "url": "https://clinicaltrials.gov/study/NCT04491240"
  },
  {
    "nct": "NCT06612710",
    "title": "The Safety and Efficacy of NouvSoma001 in Ischemic Stroke",
    "ev_source": "Neural Stem Cells",
    "dose_raw": 300000000000.0,
    "dose_unit": "particles/kg",
    "dose_scaled": 300000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": "https://clinicaltrials.gov/study/NCT06612710"
  },
  {
    "nct": "NCT04544215",
    "title": "A Clinical Study of Mesenchymal Progenitor Cell Exosomes Nebulizer for the Treatment of Pulmonary Infection",
    "ev_source": "Mesenchymal Precursor Cells (MPCs)",
    "dose_raw": 1600000000.0,
    "dose_unit": "nanovesicles/3 mL",
    "dose_scaled": 1600000000.0,
    "axis": "particles",
    "route": "Inhalation",
    "url": "https://clinicaltrials.gov/study/NCT04544215"
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 1200000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 1200000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": ""
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 1200000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 1200000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": ""
  },
  {
    "nct": "NCT04657406",
    "title": "Expanded Access to Zofin for Patients With COVID-19",
    "ev_source": "Human amniotic fluid (HAF)",
    "dose_raw": 500000000000.0,
    "dose_unit": "particles",
    "dose_scaled": 500000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": "https://clinicaltrials.gov/study/NCT04657406"
  },
  {
    "nct": "NCT04384445",
    "title": "Zofin (Organicell Flow) for Patients With COVID-19",
    "ev_source": "Amniotic stem and Epithelial cells derived exosomes",
    "dose_raw": 500000000000.0,
    "dose_unit": "particles/mL",
    "dose_scaled": 500000000000.0,
    "axis": "particles",
    "route": "Intravenous",
    "url": "https://clinicaltrials.gov/study/NCT04384445"
  },
  {
    "nct": "NCT05043181",
    "title": "Exosome-based Nanoplatform for Ldlr mRNA Delivery in FH",
    "ev_source": "Bone Marrow Derived Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 29600.0,
    "dose_unit": "mg/kg",
    "dose_scaled": 29600.0,
    "axis": "weight_ug",
    "route": "Intravenous",
    "url": "https://clinicaltrials.gov/study/NCT05043181"
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 150000.0,
    "dose_unit": "µg",
    "dose_scaled": 150000.0,
    "axis": "weight_ug",
    "route": "Intradermal / topical",
    "url": ""
  },
  {
    "nct": "NCT03437759",
    "title": "MSC-Exos Promote Healing of MHs",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 20.0,
    "dose_unit": "µg MSC-Exo",
    "dose_scaled": 20.0,
    "axis": "weight_ug",
    "route": "Other",
    "url": "https://clinicaltrials.gov/study/NCT03437759"
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 150000.0,
    "dose_unit": "µg",
    "dose_scaled": 150000.0,
    "axis": "weight_ug",
    "route": "Intradermal / topical",
    "url": ""
  },
  {
    "nct": "NCT06242379",
    "title": "Safety and Efficacy of Stem Cell Small Extracellular Vesicles in Patients With Retinitis Pigmentosa",
    "ev_source": "Bone Marrow Derived Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 50.0,
    "dose_unit": "µg sEVs",
    "dose_scaled": 50.0,
    "axis": "weight_ug",
    "route": "Other",
    "url": "https://clinicaltrials.gov/study/NCT06242379"
  },
  {
    "nct": "",
    "title": "Source trial not identified",
    "ev_source": "",
    "dose_raw": 2.5,
    "dose_unit": "µg",
    "dose_scaled": 2.5,
    "axis": "weight_ug",
    "route": "Intradermal / topical",
    "url": ""
  },
  {
    "nct": "NCT05669144",
    "title": "Co-transplantation of Mesenchymal Stem Cell Derived Exosomes and Autologous Mitochondria for Patients Candidate for CABG Surgery",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 100.0,
    "dose_unit": "µg exosomes",
    "dose_scaled": 100.0,
    "axis": "weight_ug",
    "route": "Other",
    "url": "https://clinicaltrials.gov/study/NCT05669144"
  },
  {
    "nct": "NCT03437759",
    "title": "MSC-Exos Promote Healing of MHs",
    "ev_source": "Mesenchymal Stem Cells (MSCs)",
    "dose_raw": 50.0,
    "dose_unit": "µg MSC-Exo",
    "dose_scaled": 50.0,
    "axis": "weight_ug",
    "route": "Other",
    "url": "https://clinicaltrials.gov/study/NCT03437759"
  },
  {
    "nct": "NCT05969717",
    "title": "Induced Pluripotent Stem Cell Derived Exosomes for the Treatment of Atopic Dermatitis",
    "ev_source": "Induced Pluripotent Stem Cells",
    "dose_raw": 50.0,
    "dose_unit": "µg/mL GD-iEXo-001",
    "dose_scaled": 50.0,
    "axis": "weight_ug",
    "route": "Intradermal / topical",
    "url": "https://clinicaltrials.gov/study/NCT05969717"
  }
];
