window.FIG3BC = [
  {
    "doi": "10.1007/s11095-014-1593-y",
    "year": "2015",
    "source": "Pharmaceutical Research",
    "cell_source": "brain endothelial bEND.3",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 0.73,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1007/s11095-014-1593-y"
  },
  {
    "doi": "10.1016/j.biomaterials.2013.11.083",
    "year": "2014",
    "source": "Biomaterials",
    "cell_source": "DC cells",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 10.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.biomaterials.2013.11.083"
  },
  {
    "doi": "10.1016/j.nano.2015.10.012",
    "year": "2016",
    "source": "Nanomedicine: Nanotechnology, Biology, and Medicine",
    "cell_source": "RAW 264.7",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 28.29,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.nano.2015.10.012"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "cow milk",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 6.027,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "brain endothelial bEND.3",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "rhodamine",
    "lc": 0.79,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1186/s12951-019-0563-2",
    "year": "2020",
    "source": "Journal of Nanobiotechnology",
    "cell_source": "HEK",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "5-FLUOROUracil",
    "lc": 3.1,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1186/s12951-019-0563-2"
  },
  {
    "doi": "10.1016/j.nano.2017.09.011",
    "year": "2018",
    "source": "Nanomedicine: Nanotechnology, Biology, and Medicine",
    "cell_source": "RAW 264.7",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 33.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.nano.2017.09.011"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "buffalo milk",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 4.6766,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "brain endothelial bEND.3",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 13.2,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.2217/nnm-2016-0154",
    "year": "2016",
    "source": "Nanomedicine",
    "cell_source": "MDA-MB-231",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 0.1138,
    "unit": "wt/wt",
    "link": "https://doi.org/10.2217/nnm-2016-0154"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "RAW264.8",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 3.2583,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 9.4693,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.nano.2017.03.001",
    "year": "2017",
    "source": "Nanomedicine: Nanotechnology, Biology, and Medicine",
    "cell_source": "Milk Derived",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 7.9,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.nano.2017.03.001"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "RAW 264.7",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 5.3,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "cow milk",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 4.8853,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 4.1017,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.jconrel.2018.08.035",
    "year": "2018",
    "source": "Journal of Controlled Release",
    "cell_source": "Blood Exosomes",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "Dopamine",
    "lc": 19.0051,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.jconrel.2018.08.035"
  },
  {
    "doi": "10.1080/10717544.2021.1951894",
    "year": "2021",
    "source": "Drug Delivery",
    "cell_source": "A549 cells",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "Docetaxel",
    "lc": 0.732,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1080/10717544.2021.1951894"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "buffalo milk",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 3.891,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 9.1275,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1038/s41929-019-0333-4",
    "year": "2019",
    "source": "Nature Catalysis",
    "cell_source": "A549 cells",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "Palladium nanosheets",
    "lc": 64.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1038/s41929-019-0333-4"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 6.7587,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 11.3963,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1186/s12951-019-0526-7",
    "year": "2019",
    "source": "Journal of Nanobiotechnology",
    "cell_source": "H-Monocyte Derived Macrophages",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 16.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1186/s12951-019-0526-7"
  },
  {
    "doi": "10.1016/j.lfs.2020.118369",
    "year": "2020",
    "source": "Life Sciences",
    "cell_source": "murine bone marrow derived MSCs",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 17.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.lfs.2020.118369"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "U-87 cell derived exosomes",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 0.92,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 10.5891,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1208/s12248-017-0154-9",
    "year": "2017",
    "source": "AAPS Journal",
    "cell_source": "bovine milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "Curcumin",
    "lc": 21.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1208/s12248-017-0154-9"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "murine bone marrow derived MSCs",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 21.0,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1021/acs.molpharmaceut.3c00132",
    "year": "2023",
    "source": "Molecular Pharmaceutics",
    "cell_source": "umbilicalcord blood (UCB)-derived M1 macrophage exosomes",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "cisplatin",
    "lc": 30.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1021/acs.molpharmaceut.3c00132"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 10.1909,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.yexmp.2016.05.013",
    "year": "2016",
    "source": "Experimental and Molecular Pathology",
    "cell_source": "bovine milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "Celastrol",
    "lc": 19.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.yexmp.2016.05.013"
  },
  {
    "doi": "10.2147/IJN.S395246",
    "year": "2023",
    "source": "International Journal of Nanomedicine",
    "cell_source": "BMSC",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "Rifampin",
    "lc": 18.8,
    "unit": "wt/wt",
    "link": "https://doi.org/10.2147/IJN.S395246"
  },
  {
    "doi": "10.1016/j.ijpharm.2023.123283",
    "year": "2023",
    "source": "International Journal of Pharmaceutics",
    "cell_source": "Human umbilical cord mesenchymal stem cells",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "Berberine",
    "lc": 17.744,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.ijpharm.2023.123283"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 9.3248,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "RAW 264.7",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 1.44,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.actbio.2023.06.004",
    "year": "2023",
    "source": "Acta Biomaterialia",
    "cell_source": "primary BMSC",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "Ce6",
    "lc": 0.46,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.actbio.2023.06.004"
  },
  {
    "doi": "10.1016/j.lfs.2024.122638",
    "year": "2024",
    "source": "Life Sciences",
    "cell_source": "milk Derived",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "Resveratrol",
    "lc": 22.6994,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.lfs.2024.122638"
  },
  {
    "doi": "10.7150/thno.30716",
    "year": "2019",
    "source": "Theranostics",
    "cell_source": "RAW264.7",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 0.8083,
    "unit": "wt/wt",
    "link": "https://doi.org/10.7150/thno.30716"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "primary BMSC",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "GW4869",
    "lc": 0.2,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HPV-16 E6/E7 transformed human bone marrow mesenchymal stromal cell line HS-5",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "Pyridine",
    "lc": 0.0344,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1021/acs.molpharmaceut.1c00182",
    "year": "2022",
    "source": "Molecular Pharmaceutics",
    "cell_source": "cow milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 6.0698,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1021/acs.molpharmaceut.1c00182"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "buffalo milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 4.0966,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.3791/58814",
    "year": "2018",
    "source": "Journal of Visualized Experiments",
    "cell_source": "HEK",
    "method": "Electroporation",
    "molecule": "Oligonucleotide",
    "drug": "siRNA",
    "lc": 0.732,
    "unit": "wt/wt",
    "link": "https://doi.org/10.3791/58814"
  },
  {
    "doi": "10.1016/j.jconrel.2024.07.066",
    "year": "2024",
    "source": "Journal of Controlled Release",
    "cell_source": "hair follicle stem cell",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "finasteride",
    "lc": 5.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.jconrel.2024.07.066"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 8.7451,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.foodchem.2023.137963",
    "year": "2024",
    "source": "Food Chemistry",
    "cell_source": "seasame seeds",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "luteolin",
    "lc": 20.5,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.foodchem.2023.137963"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 5.4678,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "tomato",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "Curcumin",
    "lc": 1.1,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 8.4729,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.jsps.2024.102096",
    "year": "2024",
    "source": "Saudi Pharmaceutical Journal",
    "cell_source": "human plasma-derived exosomes",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "Methotrexate",
    "lc": 16.33,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.jsps.2024.102096"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 10.4607,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 7.7844,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1080/03639045.2020.1776320",
    "year": "2020",
    "source": "Drug Development and Industrial Pharmacy",
    "cell_source": "monocytes from UCB mononuclear cells",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "Cisplatin",
    "lc": 30.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1080/03639045.2020.1776320"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 7.8604,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Milk Derived",
    "method": "Sonication",
    "molecule": "Protein",
    "drug": "semaglutide",
    "lc": 28.0,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "goat milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 7.3308,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "MSC",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "5‑fluorouracil",
    "lc": 6.7763,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1007/s40199-019-00280-5",
    "year": "2019",
    "source": "DARU, Journal of Pharmaceutical Sciences",
    "cell_source": "U-87 cell derived exosomes",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 0.74,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1007/s40199-019-00280-5"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HPV-16 E6/E7 transformed human bone marrow mesenchymal stromal cell line HS-5",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "Pyridine",
    "lc": 0.1204,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.biopha.2022.113690",
    "year": "2022",
    "source": "Biomedicine and Pharmacotherapy",
    "cell_source": "HEK",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 4.706,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.biopha.2022.113690"
  },
  {
    "doi": "10.1016/j.jconrel.2021.07.004",
    "year": "2021",
    "source": "Journal of Controlled Release",
    "cell_source": "bEnd.3",
    "method": "Sonication",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 9.49,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.jconrel.2021.07.004"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 7.231,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 19.87,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 15.1,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 16.23,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 14.51,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1248/bpb.b23-00135",
    "year": "2023",
    "source": "Biological and Pharmaceutical Bulletin",
    "cell_source": "B16F1",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 23.55,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1248/bpb.b23-00135"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Human umbilical cord mesenchymal stem cells",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "Berberine",
    "lc": 4.6682,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.3390/ph16010108",
    "year": "2023",
    "source": "Pharmaceuticals",
    "cell_source": "RAW264",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 7.21,
    "unit": "wt/wt",
    "link": "https://doi.org/10.3390/ph16010108"
  },
  {
    "doi": "10.2147/IJN.S444686",
    "year": "2024",
    "source": "International Journal of Nanomedicine",
    "cell_source": "Kaempferia parviflora",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "clarithromycin",
    "lc": 1.6,
    "unit": "wt/wt",
    "link": "https://doi.org/10.2147/IJN.S444686"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Kaempferia parviflora",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "clarithromycin",
    "lc": 9.3,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Kaempferia parviflora",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "clarithromycin",
    "lc": 93.45,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1039/d2bm01558g",
    "year": "2023",
    "source": "Biomaterials Science",
    "cell_source": "goat milk",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "indocyanine green",
    "lc": 4.124,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1039/d2bm01558g"
  },
  {
    "doi": "10.1016/j.biopha.2024.116403",
    "year": "2024",
    "source": "Biomedicine and Pharmacotherapy",
    "cell_source": "Y79 Retinoblastoma",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "carboplatin",
    "lc": 51.69,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.biopha.2024.116403"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Y79 Retinoblastoma",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "carboplatin",
    "lc": 31.34,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Y79 Retinoblastoma",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "carboplatin",
    "lc": 40.08,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Y79 Retinoblastoma",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "carboplatin",
    "lc": 11.0,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Y79 Retinoblastoma",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "carboplatin",
    "lc": 17.9,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Y79 Retinoblastoma",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "carboplatin",
    "lc": 18.43,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Y79 Retinoblastoma",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "carboplatin",
    "lc": 14.8,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Y79 Retinoblastoma",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "carboplatin",
    "lc": 13.04,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.biopha.2024.116403",
    "year": "2024",
    "source": "Biomedicine and Pharmacotherapy",
    "cell_source": "Y79 Retinoblastoma",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "carboplatin",
    "lc": 12.94,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.biopha.2024.116403"
  },
  {
    "doi": "10.1016/j.jconrel.2024.05.024",
    "year": "2024",
    "source": "Journal of Controlled Release",
    "cell_source": "milk Derived",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "pirfenidone",
    "lc": 6.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.jconrel.2024.05.024"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "milk Derived",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "18β-glycyrrhetinic acid",
    "lc": 8.68,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "tomato",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "Curcumin",
    "lc": 3.6,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.3892/mmr.2022.12729",
    "year": "2022",
    "source": "Molecular Medicine Reports",
    "cell_source": "MSC",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "5‑fluorouracil",
    "lc": 0.0409,
    "unit": "wt/wt",
    "link": "https://doi.org/10.3892/mmr.2022.12729"
  },
  {
    "doi": "10.1002/adhm.202100047",
    "year": "2022",
    "source": "Advanced Healthcare Materials",
    "cell_source": "HPV-16 E6/E7 transformed human bone marrow mesenchymal stromal cell line HS-5",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "Pyridine",
    "lc": 0.4814,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1002/adhm.202100047"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HPV-16 E6/E7 transformed human bone marrow mesenchymal stromal cell line HS-5",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "Pentoxifylline",
    "lc": 1.012,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.jconrel.2015.09.031",
    "year": "2015",
    "source": "Journal of Controlled Release",
    "cell_source": "Pca",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 0.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.jconrel.2015.09.031"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Immune cells",
    "method": "Passive diffusion",
    "molecule": "Protein",
    "drug": "Catalase",
    "lc": 8.17,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1126/sciadv.abp9435",
    "year": "2022",
    "source": "Science Advances",
    "cell_source": "hepatic stellate cells (HSCs",
    "method": "Electroporation",
    "molecule": "Protein",
    "drug": "Cas 9 RNP",
    "lc": 4.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1126/sciadv.abp9435"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Immune cells",
    "method": "Sonication",
    "molecule": "Protein",
    "drug": "Catalase",
    "lc": 43.5,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.jconrel.2015.03.033",
    "year": "2015",
    "source": "Journal of Controlled Release",
    "cell_source": "Immune cells",
    "method": "Chemical permeabilization",
    "molecule": "Protein",
    "drug": "Catalase",
    "lc": 30.83,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.jconrel.2015.03.033"
  },
  {
    "doi": "10.1126/sciadv.aaz0748",
    "year": "2020",
    "source": "Science Advances",
    "cell_source": "RAW",
    "method": "Genetic",
    "molecule": "Protein",
    "drug": "IL-10",
    "lc": 0.11,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1126/sciadv.aaz0748"
  },
  {
    "doi": "10.1021/acsnano.4c02560",
    "year": "2024",
    "source": "ACS Nano",
    "cell_source": "Milk Derived",
    "method": "Sonication",
    "molecule": "Protein",
    "drug": "semaglutide",
    "lc": 40.5,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1021/acsnano.4c02560"
  },
  {
    "doi": "10.1016/j.jconrel.2018.04.037",
    "year": "2018",
    "source": "Journal of Controlled Release",
    "cell_source": "HEK 293",
    "method": "Genetic",
    "molecule": "Protein",
    "drug": "SIRPα protein",
    "lc": 0.5098,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.jconrel.2018.04.037"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Milk Derived",
    "method": "Sonication",
    "molecule": "Protein",
    "drug": "semaglutide",
    "lc": 32.8,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1002/adfm.201703074",
    "year": "2018",
    "source": "Advanced Functional Materials",
    "cell_source": "HEK 293",
    "method": "Genetic",
    "molecule": "Protein",
    "drug": "PH20 Protein",
    "lc": 0.53,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1002/adfm.201703074"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "Milk Derived",
    "method": "Sonication",
    "molecule": "Protein",
    "drug": "semaglutide",
    "lc": 31.8,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "MSC",
    "method": "Sonication",
    "molecule": "Protein",
    "drug": "G7 functionalized poly(amidoamine) (PAMAM) dendrimers NH2",
    "lc": 32.3,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "MSC",
    "method": "Sonication",
    "molecule": "Protein",
    "drug": "G2 functionalized poly(amidoamine) (PAMAM) dendrimers COOH",
    "lc": 0.25,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "SF7761 stem cells-like",
    "method": "Chemical permeabilization",
    "molecule": "Small molecule",
    "drug": "DOX",
    "lc": 0.11,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1186/s12951-019-0526-7",
    "year": "2019",
    "source": "Journal of Nanobiotechnology",
    "cell_source": "H-Monocyte Derived Macrophages",
    "method": "Passive diffusion",
    "molecule": "Oligonucleotide",
    "drug": "Cholesterol-miRNA",
    "lc": 5.38,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1186/s12951-019-0526-7"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "FBS",
    "method": "Electroporation",
    "molecule": "Small molecule",
    "drug": "Astaxanthin",
    "lc": 0.5,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK293T",
    "method": "Sonication",
    "molecule": "Oligonucleotide",
    "drug": "miRNA",
    "lc": 0.45,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK293T",
    "method": "Genetic",
    "molecule": "Oligonucleotide",
    "drug": "siRNA",
    "lc": 0.196,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "H-Monocyte Derived Macrophages",
    "method": "Passive diffusion",
    "molecule": "Oligonucleotide",
    "drug": "miRNA",
    "lc": 1.22,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.jconrel.2013.08.014",
    "year": "2013",
    "source": "Journal of Controlled Release",
    "cell_source": "HEK /N2A",
    "method": "Electroporation",
    "molecule": "Oligonucleotide",
    "drug": "siRNA",
    "lc": 3.7,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.jconrel.2013.08.014"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "MSC",
    "method": "Sonication",
    "molecule": "Protein",
    "drug": "G7 functionalized poly(amidoamine) (PAMAM) dendrimers Ac",
    "lc": 0.63,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK293T-RVG",
    "method": "Genetic",
    "molecule": "Oligonucleotide",
    "drug": "siRNA",
    "lc": 0.21,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.2147/IJN.S154458",
    "year": "2018",
    "source": "International Journal of Nanomedicine",
    "cell_source": "HEK293T",
    "method": "Electroporation",
    "molecule": "Oligonucleotide",
    "drug": "miRNA",
    "lc": 0.297,
    "unit": "wt/wt",
    "link": "https://doi.org/10.2147/IJN.S154458"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK293T",
    "method": "Passive diffusion",
    "molecule": "Oligonucleotide",
    "drug": "miRNA",
    "lc": 0.14,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1038/nbt.1807",
    "year": "2011",
    "source": "Nature Biotechnology",
    "cell_source": "Dentritic Cells",
    "method": "Electroporation",
    "molecule": "Oligonucleotide",
    "drug": "siRNA",
    "lc": 25.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1038/nbt.1807"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "breast cancer cell line (MCF7)",
    "method": "Sonication",
    "molecule": "Protein",
    "drug": "G4 functionalized poly(amidoamine) (PAMAM) dendrimers COOH",
    "lc": 0.25,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK293T",
    "method": "Passive diffusion",
    "molecule": "Oligonucleotide",
    "drug": "siRNA",
    "lc": 0.22,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1021/acs.molpharmaceut.5b00364",
    "year": "2015",
    "source": "Molecular Pharmaceutics",
    "cell_source": "HEK",
    "method": "Electroporation",
    "molecule": "DNA",
    "drug": "250 bp DNA",
    "lc": 0.7071,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1021/acs.molpharmaceut.5b00364"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK293T",
    "method": "Passive diffusion",
    "molecule": "DNA",
    "drug": "ssDNA",
    "lc": 0.11,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1016/j.biomaterials.2016.09.031",
    "year": "2016",
    "source": "Biomaterials",
    "cell_source": "B16BL6 cells",
    "method": "Passive diffusion",
    "molecule": "DNA",
    "drug": "CpG 20 DNA",
    "lc": 0.6138,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.biomaterials.2016.09.031"
  },
  {
    "doi": "10.1016/j.jconrel.2017.09.013",
    "year": "2017",
    "source": "Journal of Controlled Release",
    "cell_source": "SKOV-3",
    "method": "Electroporation",
    "molecule": "DNA",
    "drug": "Plasmid",
    "lc": 3.3333,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1016/j.jconrel.2017.09.013"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "breast cancer cell line (MCF7)",
    "method": "Sonication",
    "molecule": "Protein",
    "drug": "G7 functionalized poly(amidoamine) (PAMAM) dendrimers COOH",
    "lc": 0.25,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.3390/mi10110750",
    "year": "2019",
    "source": "Micromachines",
    "cell_source": "HEK",
    "method": "Passive diffusion",
    "molecule": "DNA",
    "drug": "DNA-FAM",
    "lc": 0.0,
    "unit": "wt/wt",
    "link": "https://doi.org/10.3390/mi10110750"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK",
    "method": "Electroporation",
    "molecule": "DNA",
    "drug": "500 bp DNA",
    "lc": 0.45,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK",
    "method": "Electroporation",
    "molecule": "DNA",
    "drug": "750 bp DNA",
    "lc": 0.4,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.22034/NMRJ.2019.04.006",
    "year": "2019",
    "source": "Nanomedicine Research Journal",
    "cell_source": "U87 derived exosomes",
    "method": "Passive diffusion",
    "molecule": "Small molecule",
    "drug": "PTX",
    "lc": 0.11,
    "unit": "wt/wt",
    "link": "https://doi.org/10.22034/NMRJ.2019.04.006"
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK",
    "method": "Electroporation",
    "molecule": "DNA",
    "drug": "1000 bp DNA",
    "lc": 0.37,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK",
    "method": "Electroporation",
    "molecule": "DNA",
    "drug": "1500 bp DNA",
    "lc": 0.05,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "",
    "year": "",
    "source": "",
    "cell_source": "HEK",
    "method": "Electroporation",
    "molecule": "DNA",
    "drug": "4000 bp DNA",
    "lc": 0.02,
    "unit": "wt/wt",
    "link": ""
  },
  {
    "doi": "10.1038/s41467-018-04791-8",
    "year": "2018",
    "source": "Nature Communications",
    "cell_source": "RBC",
    "method": "Electroporation",
    "molecule": "Oligonucleotide",
    "drug": "ASO",
    "lc": 0.01,
    "unit": "wt/wt",
    "link": "https://doi.org/10.1038/s41467-018-04791-8"
  }
];
